FROM python:3.7

ADD . /
RUN rm -rf /var/lib/apt/lists/* && \
	apt-get clean && \
	apt-get update && \
	apt-get install -y --fix-missing --allow-unauthenticated libgl1-mesa-dev
RUN pip install cython && \
	pip install -r requirements_linux.txt

CMD [ "python", "callllama.py" ]

